import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import multipart from '@fastify/multipart';
import prismaPlugin from './plugins/prisma.js';
import { env } from './config/env.js';
import { authRoutes } from './routes/auth.js';
import { lifeRoutes } from './routes/life.js';
import { assistantRoutes } from './routes/assistant.js';
import { documentRoutes } from './routes/documents.js';
import { expansionRoutes } from './routes/expansion.js';
import { healthExpansionRoutes } from './routes/health-expansion.js';

const app = Fastify({ logger:true, bodyLimit:2*1024*1024 });
await app.register(helmet);
await app.register(cors,{origin:env.WEB_ORIGIN,credentials:true});
await app.register(rateLimit,{max:100,timeWindow:'1 minute'});
await app.register(multipart,{limits:{fileSize:25*1024*1024,files:1}});
await app.register(prismaPlugin);
app.setErrorHandler((error,request,reply)=>{request.log.error(error);const status=(error as any).statusCode??(error.name==='ZodError'?400:500);reply.code(status).send({error:status>=500?'Internal server error':error.message});});
app.get('/health',async()=>({ok:true,service:'lifeos-api',version:'1.6.0'}));
app.get('/api/v1',async()=>({name:'LIFEOS API',version:'v1',capabilities:['auth','dashboard','search','documents','memories','tasks','assets','assistant','integrations','timeline','inbox','finance','notifications','automations','sync','sync-history','life-overview']}));
await app.register(authRoutes,{prefix:'/api/v1/auth'});
await app.register(lifeRoutes,{prefix:'/api/v1'});
await app.register(documentRoutes,{prefix:'/api/v1/documents'});
await app.register(assistantRoutes,{prefix:'/api/v1/assistant'});
await app.register(expansionRoutes,{prefix:'/api/v1'});
await app.register(healthExpansionRoutes,{prefix:'/api/v1'});
await app.listen({port:env.PORT,host:'0.0.0.0'});
